name: Benchmarks

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0' # weekly on Sundays at 03:00 UTC (optional)

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install hyperfine
        run: sudo apt-get update && sudo apt-get install -y hyperfine

      - name: Run benchmarks
        run: |
          chmod +x scripts/bench-tools.sh
          ./scripts/bench-tools.sh "echo foo" "printf foo" || true

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: bench-results
          path: bench-results.json
