name: CI

on:
  push:
    branches: [ main, 'chore/**' ]
  pull_request:
    branches: [ main ]

jobs:
  api-server:
    name: API Server Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./api-server
        run: npm ci

      - name: Run tests
        working-directory: ./api-server
        run: npm test

  vscode-extension:
    name: VS Code Extension Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./vscode-extension
        run: npm ci

      - name: Compile extension
        working-directory: ./vscode-extension
        run: npm run compile

  quarto-render:
    name: Quarto Render (docs)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Quarto and Render
        uses: quarto-dev/quarto-actions@v2
        with:
          command: render
          args: --no-execute --to html

      - name: Upload HTML book as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-book
          path: _book
